In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('All.csv')
dataset.shape

(36707, 80)

In [15]:
dataset

Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
35               0                   4                 4           6.250000   
37              22                   4                10           6.250000   
38              23                   4                10           6.250000   
39              22                   4                10           6.250000   
40              23                   4                10           6.250000   
...            ...                 ...               ...                ...   
36702           29                   4                14           5.750000   
36703            0                   4                13           3.750000   
36704           58                   3                27           6.666666   
36705           35                   3                13           4.333334   
36706           40                   3                25           6.666666   

       longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
35                     17         3.750000    4               4            2   
37                     17         3.500000    4              19           10   
38                     17         3.500000    4              19           10   
39                     17         3.500000    4              19           10   
40                     17         3.500000    4              19           10   
...                   ...              ...  ...             ...          ...   
36702                  12         3.666667    4              20           24   
36703                   8         8.461538    4              24           23   
36704                  16         3.375000    3              41           34   
36705                   9         3.600000    3              15           13   
36706                  16         3.250000    3              35           31   

       ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
35           0  ...                     1                      0   
37           0  ...                     9                      8   
38           0  ...                     9                      8   
39           0  ...                     9                      8   
40           0  ...                     9                      8   
...        ...  ...                   ...                    ...   
36702        3  ...                     3                      2   
36703        0  ...                    16                     15   
36704       20  ...                     8                      7   
36705        7  ...                     9                      8   
36706       19  ...                     7                      6   

       SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
35                        -1     0.726945        0.768811   
37                         7     0.686486        0.768811   
38                         7     0.687286        0.768811   
39                         7     0.683476        0.768811   
40                         7     0.687286        0.768811   
...                      ...          ...             ...   
36702                      7     0.690555        0.791265   
36703                     -1     0.665492        0.820010   
36704                      9     0.656807        0.801139   
36705                      3     0.725963        0.897617   
36706                      7     0.674351        0.801139   

       Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
35                  0.916667          1.000000           1.000000   
37                  0.916667          0.748105           0.757206   
38                  0.916667          0.747622           0.756298   
39                  0.916667          0.742090           0.750292   
40                  0.916667          0.747622           0.756298   
...                      ...               ...                ...   
36702               0.777498          0.690227           0.65668

In [3]:
##delete Nan values and seperate x and y
# y as result
dataset = pd.DataFrame(dataset)
dataset.dropna(inplace = True)
x = dataset.iloc[:, 0:79].values
y = dataset.iloc[:, 79].values
y=pd.DataFrame(y)

In [18]:
x

array([[ 0.        ,  4.        ,  4.        , ...,  1.        ,
         1.        , -1.        ],
       [22.        ,  4.        , 10.        , ...,  0.74810535,
         0.7572058 ,  0.74916678],
       [23.        ,  4.        , 10.        , ...,  0.74762222,
         0.75629805,  0.74826769],
       ...,
       [58.        ,  3.        , 27.        , ...,  0.7136219 ,
         0.7171868 ,  0.70524456],
       [35.        ,  3.        , 13.        , ...,  0.7459324 ,
         0.75882363,  0.79077169],
       [40.        ,  3.        , 25.        , ...,  0.73056291,
         0.73148101,  0.76923786]])

In [4]:
##StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x)

In [5]:
from sklearn.decomposition import PCA


In [14]:
x

array([[ 0.        ,  4.        ,  4.        , ...,  1.        ,
         1.        , -1.        ],
       [22.        ,  4.        , 10.        , ...,  0.74810535,
         0.7572058 ,  0.74916678],
       [23.        ,  4.        , 10.        , ...,  0.74762222,
         0.75629805,  0.74826769],
       ...,
       [58.        ,  3.        , 27.        , ...,  0.7136219 ,
         0.7171868 ,  0.70524456],
       [35.        ,  3.        , 13.        , ...,  0.7459324 ,
         0.75882363,  0.79077169],
       [40.        ,  3.        , 25.        , ...,  0.73056291,
         0.73148101,  0.76923786]])

In [8]:
def PCA_component(n_components):
    pca = PCA(n_components)
    print(pca)
    pca.fit(x)
    X_transformed = pca.transform(x)
    print(pca.explained_variance_ratio_)

In [9]:
PCA_component(5)

PCA(n_components=5)
[0.97695789 0.01056075 0.00337112 0.00278028 0.00189729]


In [10]:
PCA_component(10)

PCA(n_components=10)
[9.76957891e-01 1.05607477e-02 3.37111698e-03 2.78028081e-03
 1.89728945e-03 1.29695100e-03 8.23179094e-04 4.47562136e-04
 3.77144010e-04 2.54385943e-04]


In [11]:
PCA_component(20)

PCA(n_components=20)
[9.76957891e-01 1.05607477e-02 3.37111698e-03 2.78028081e-03
 1.89728945e-03 1.29695100e-03 8.23179094e-04 4.47562136e-04
 3.77144010e-04 2.54385944e-04 1.78443239e-04 1.49769006e-04
 1.36706173e-04 1.04060316e-04 9.62778972e-05 9.01164984e-05
 8.77699602e-05 6.26388012e-05 5.25452700e-05 4.40033897e-05]


In [12]:
PCA_component(50)

PCA(n_components=50)
[9.76957891e-01 1.05607477e-02 3.37111698e-03 2.78028081e-03
 1.89728945e-03 1.29695100e-03 8.23179094e-04 4.47562136e-04
 3.77144010e-04 2.54385944e-04 1.78443239e-04 1.49769006e-04
 1.36706173e-04 1.04060316e-04 9.62778972e-05 9.01164984e-05
 8.77699602e-05 6.26388016e-05 5.25452704e-05 4.40033918e-05
 3.58127372e-05 3.07698527e-05 2.48859884e-05 1.93511810e-05
 1.57952064e-05 1.53201472e-05 1.41216305e-05 1.23135748e-05
 1.00244302e-05 9.25891721e-06 5.96689197e-06 5.26026468e-06
 4.49991978e-06 3.83181353e-06 3.61730200e-06 3.14973043e-06
 2.66712910e-06 2.14258293e-06 2.08572142e-06 1.43098062e-06
 1.29167416e-06 1.19154162e-06 1.08702029e-06 9.95027691e-07
 6.85626061e-07 6.21434797e-07 5.51557549e-07 4.58109601e-07
 4.26896719e-07 2.86510867e-07]


In [13]:
PCA_component(79)

PCA(n_components=79)
[9.76957891e-01 1.05607477e-02 3.37111698e-03 2.78028081e-03
 1.89728945e-03 1.29695100e-03 8.23179094e-04 4.47562136e-04
 3.77144010e-04 2.54385944e-04 1.78443239e-04 1.49769006e-04
 1.36706173e-04 1.04060316e-04 9.62778972e-05 9.01164984e-05
 8.77699602e-05 6.26388016e-05 5.25452704e-05 4.40033918e-05
 3.58127372e-05 3.07698527e-05 2.48859884e-05 1.93511810e-05
 1.57952064e-05 1.53201472e-05 1.41216305e-05 1.23135748e-05
 1.00244302e-05 9.25891721e-06 5.96689197e-06 5.26026468e-06
 4.49991978e-06 3.83181353e-06 3.61730200e-06 3.14973043e-06
 2.66712910e-06 2.14258293e-06 2.08572142e-06 1.43098062e-06
 1.29167416e-06 1.19154162e-06 1.08702029e-06 9.95027691e-07
 6.85626061e-07 6.21434797e-07 5.51557549e-07 4.58109601e-07
 4.26896719e-07 2.86510867e-07 2.52296966e-07 2.12034979e-07
 1.43872234e-07 1.26314709e-07 1.07235255e-07 8.86953328e-08
 6.17604563e-08 4.37812637e-08 3.67509107e-08 2.92047783e-08
 2.05009298e-08 1.67506685e-08 1.62097657e-08 1.54129574e-08
 1.

In [21]:
pca = PCA(5)
print(pca)
pca.fit(x)
X_transformed = pca.transform(x)
X_transformed

PCA(n_components=5)


array([[-1.36574520e+02, -3.85016355e+01,  2.45101061e+00,
        -4.96620285e+00, -1.19464728e+01],
       [-2.42622820e+01, -4.05684557e+00, -2.03211527e+01,
         3.79380150e-01, -2.08887125e+01],
       [-2.21289125e+01, -3.23671219e+00, -2.10144300e+01,
        -9.23814369e-02, -1.95581004e+01],
       ...,
       [ 2.62027644e+02,  1.52865234e+02, -1.85332059e+01,
        -6.64664237e+01,  7.20219431e+00],
       [ 2.94149862e+01,  1.03297939e+01, -3.22669941e+01,
        -4.86681097e+00,  2.11011131e+01],
       [ 2.18228277e+02,  1.40768416e+02, -3.61123967e+01,
        -4.19599594e+01,  6.67050737e+00]])

In [22]:
X_transformed.shape

(18982, 5)

In [23]:
x

array([[ 0.        ,  4.        ,  4.        , ...,  1.        ,
         1.        , -1.        ],
       [22.        ,  4.        , 10.        , ...,  0.74810535,
         0.7572058 ,  0.74916678],
       [23.        ,  4.        , 10.        , ...,  0.74762222,
         0.75629805,  0.74826769],
       ...,
       [58.        ,  3.        , 27.        , ...,  0.7136219 ,
         0.7171868 ,  0.70524456],
       [35.        ,  3.        , 13.        , ...,  0.7459324 ,
         0.75882363,  0.79077169],
       [40.        ,  3.        , 25.        , ...,  0.73056291,
         0.73148101,  0.76923786]])